version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: bdt
      POSTGRES_USER: bdt
      POSTGRES_PASSWORD: bdt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: big-data-team
      MINIO_ROOT_PASSWORD: big-data-team
      MINIO_SERVER_URL: "http://localhost:9000"
      MINIO_BROWSER_REDIRECT_URL: "http://localhost:9001"
    volumes:
      - minio_data:/data
    command: server --console-address ':9001' /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  init-minio:
    image: alpine:latest
    volumes:
      - ./init-minio.sh:/init-minio.sh
    command: >
      /bin/sh -c "
        apk add --no-cache curl &&
        wget https://dl.min.io/client/mc/release/linux-amd64/mc &&
        chmod +x mc &&
        mv mc /usr/local/bin &&
       chmod +x /init-minio.sh
        /init-minio.sh
      "
    depends_on:
      - minio

  devcontainer:
    build:
      context: ./spark
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    command: sleep infinity
    depends_on:
      - postgres
      - minio
      - init-minio
volumes:
  postgres_data:
  minio_data:
